https://github.com/fluentpython/example-code-2e/blob/master/02-array-seq/listcomp_speed.py

In [5]:
x = 'ABCabcABCabc'
codes = [ord(x) for x in x]
print(codes)


test_codes = [last := ord(c) for c in x]
print(test_codes)
print(last)

[65, 66, 67, 97, 98, 99, 65, 66, 67, 97, 98, 99]
[65, 66, 67, 97, 98, 99, 65, 66, 67, 97, 98, 99]
99


In [8]:
symbols = 'ABCabcABCabc'
b_ascii = [ord(s) for s in symbols if ord(s) > 70]
print(b_ascii)

ba = list(filter(lambda c: c > 70, map(ord, symbols)))
print(ba)

[97, 98, 99, 97, 98, 99]
[97, 98, 99, 97, 98, 99]


В документе PEP 572
«Assignment Expressions» (https://peps.python.org/pep-0572/) область видимости
оператора := определена как объемлющая функция, если только соответству-
ющая переменная не является частью объявления global или nonlocal1.

In [12]:
colors = ['black', 'white']
sizes = ['s', 'm', 'l']
tshirts = [(color, size) for color in colors for size in sizes]

print(tshirts)


for color in colors:
    for size in sizes:
        print((color, size))

[('black', 's'), ('black', 'm'), ('black', 'l'), ('white', 's'), ('white', 'm'), ('white', 'l')]
('black', 's')
('black', 'm')
('black', 'l')
('white', 's')
('white', 'm')
('white', 'l')


In [ ]:
Запомните правило:
Если генераторное выражение стоит внутри скобок другой функции, и оно там одно, то его собственные скобки можно опустить. Если рядом есть запятая или другие аргументы — скобки ставить строго обязательно.


Итоговая таблица-шпаргалка
Запись	Название	Что делает
(x for x in items)	Генераторное выражение	Создает объект-генератор. Элементы вычисляются по требованию (лениво).
[x for x in items]	Списковое включение	Создает список (list). Все элементы вычисляются сразу и хранятся в памяти.
{x for x in items}	Множественное включение	Создает множество (set).
{x: y for x,y in items}	Словарное включение	Создает словарь (dict).



In [13]:
for ts in (f'{c} {s}' for c in colors for s in sizes):
    print(ts)

black s
black m
black l
white s
white m
white l


Генераторное выражение отдает по одному элементу за раз; список, содер-
жащий все шесть вариаций футболки, не создается.

In [24]:
a = (10, 'alpha', [1, 2])
b = (10, 'alpha', [1, 2])
print(a == b)

b[-1].append(99)
print(b)
print(b[-1])
print(b[-2])

True
(10, 'alpha', [1, 2, 99])
[1, 2, 99]
alpha


The Sequence Comparison Algorithm (Under the Hood)
Python's tuple comparison follows this pseudo-code:

python
def tuple_equal(t1, t2):
    # 1. Same type?
    if type(t1) != type(t2):
        return False
    
    # 2. Same length?
    if len(t1) != len(t2):
        return False
    
    # 3. Compare each element
    for item1, item2 in zip(t1, t2):
        if item1 != item2:
            return False
    
    # 4. All elements matched
    return True

Pitfall 3: == vs is
python
a = (10, 'alpha', [1, 2])
b = a  # b references the SAME object

a == b  # True (same content)
a is b  # True (same object!)

c = (10, 'alpha', [1, 2])  # New tuple
a == c  # True (same content)
a is c  # False (different objects)

In [ ]:
o = 'string'
dic = {'item': 123}
print(hash(o))

# TypeError: unhashable type: 'dict'
print(hash(dic))



-5865790574487694285


TypeError: unhashable type: 'dict'

In [27]:
a, b, *rest = range(5)
print(a,b,rest)

0 1 [2, 3, 4]


In [28]:
a, *body, c, d = range(5)
print(a, body, c, d)

0 [1, 2] 3 4


In [30]:
metro_areas = [
('Tokyo', 'JP', 36.933, (35.689722, 139.691667)),
('Delhi NCR', 'IN', 21.935, (28.613889, 77.208889)),
('Mexico City', 'MX', 20.142, (19.433333, -99.133333)),
('New York-Newark', 'US', 20.104, (40.808611, -74.020386)),
('São Paulo', 'BR', 19.649, (-23.547778, -46.635833)),
]

for item in metro_areas:
    name, *body, (lat, lon) = item
    print(name, lat, lon)

Tokyo 35.689722 139.691667
Delhi NCR 28.613889 77.208889
Mexico City 19.433333 -99.133333
New York-Newark 40.808611 -74.020386
São Paulo -23.547778 -46.635833


Если вернется 0 или 2 записи — будет ошибка:

python
def empty_query():
    return []  # Пустой результат

[record] = empty_query()  # ValueError: not enough values to unpack

def two_rows():
    return [("Alice", 25), ("Bob", 30)]

[record] = two_rows()  # ValueError: too many values to unpack
Это автоматическая проверка — вы сразу узнаете, если запрос вернул не ровно одну строку!

Почему в срезы и диапазоны не включается последний
элемент
Принятое в Python соглашение не включать последний элемент в срезы и диа-
пазоны соответствует индексации с нуля, принятой в Python, C и многих дру-
гих языках. Приведем несколько полезных следствий из этого соглашения.
 Легко понять, какова длина среза или диапазона, если задана только ко-
нечная позиция: и range(3), и my_list[:3] содержат три элемента.
 Легко вычислить длину среза или диапазона, если заданы начальная
и конечная позиции, достаточно вычислить их разность stop - start.
 Легко разбить последовательность на две непересекающиеся части по
любому индексу x: нужно просто взять my_list[:x] и my_list[x:]. Например:

Вы можете сохранить срез в переменную и использовать его повторно, не переписывая каждый раз [1:10:2].

In [ ]:
# Обычный способ (всё в одну строку)
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(data[2:8:2])  # Вывод: [2, 4, 6]

# Продвинутый способ с именованным срезом (о чем текст)
my_slice = slice(2, 8, 2)  # Сохранили настройки среза в переменную

print(data[my_slice])      # Вывод: [2, 4, 6]
data = [10, 20, 30, 40, 50, 60, 70, 80, 90]
print(data[my_slice])      # Вывод: [30, 50, 70] - применили тот же срез к новым данным!

Многомерные срезы и многоточие
Оператор [] может принимать несколько индексов или срезов, разделенных за-
пятыми. Специальные методы __getitem__ и __setitem__, на которых основан опе-
ратор [], просто принимают индексы, заданные в выражении a[i, j], в виде кор-
тежа. Иначе говоря, для вычисления a[i, j] Python вызывает a.__getitem__((i, j)).
Это используется, например, во внешнем пакете NumPy, где для получения
одного элемента двумерного массива numpy.ndarray применяется нотация a[i, j],
а для получения двумерного среза – нотация a[m:n, k:l]. В примере 2.22 ниже
будет продемонстрировано использование этой нотации.
За исключением memoryview, в Python встроены только одномерные типы по-
следовательностей, поэтому они поддерживают лишь один индекс или срез,
а не кортеж1.


А раз так, то
многоточие можно передавать в качестве аргумента функциям и использовать
в качестве части спецификации среза, например f(a, ..., z) или a[i:...]. В NumPy
… используется для сокращенного задания среза многомерного массива; напри-
мер, если x – четырехмерный массив, то x[i, ...] – то же самое, что x[i, :, :, :,].



In [ ]:
l = list(range(10))
l[2:5] = [20, 30, 40, 50]
print(l)

del l[:2]

print(l)


l[2:6] = [100]
print(l)

print(l * 3)

print('123' * 4)

# can only concatenate str (not "int") to str
print('123' + 4)



[0, 1, 20, 30, 40, 50, 5, 6, 7, 8, 9]
[20, 30, 40, 50, 5, 6, 7, 8, 9]
[20, 30, 100, 7, 8, 9]
[20, 30, 100, 7, 8, 9, 20, 30, 100, 7, 8, 9, 20, 30, 100, 7, 8, 9]
123123123123


TypeError: can only concatenate str (not "int") to str

Остерегайтесь выражений вида a * n, где a – последователь-
ность, содержащая изменяемые элементы, потому что резуль-
тат может оказаться неожиданным. Например, при попытке
инициа­лизировать список списков my_list = [[]] * 3 получится
список, содержащий три ссылки на один и тот же внутренний
список, хотя вы, скорее всего, хотели не этого.

In [13]:
my_list = [[]] * 3

print(my_list)

print(['_'] * 3)

[[], [], []]
['_', '_', '_']


In [ ]:
# Список, содержащий три ссылки на один и тот же список, бесполезен

weird_board = [['_'] * 3] * 3
print(weird_board)

weird_board[1][2] = 'O'

print(weird_board)


[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
[['_', '_', 'O'], ['_', '_', 'O'], ['_', '_', 'O']]


In [18]:
t = (1,2,3)
print(id(t))

t *=2

print(t)
print(id(t))

128979348433472
(1, 2, 3, 1, 2, 3)
128979347953440


In [ ]:
t = (1, 2, [30, 40])
# t[2] += [50, 60]
# 'tuple' object does not support item assignment
print(t)

t = (1, 2, [30, 40])
t[2].extend([50,60]) # without errors
print(t)


(1, 2, [30, 40])
(1, 2, [30, 40, 50, 60])


Метод list.sort и встроенная функция sorted
Метод list.sort сортирует список на месте, т. е. не создавая копию. Он возвра-
щает None, напоминая, что изменяет объект-приемник1, а не создает новый
список. Это важное соглашение в Python API: функции и методы, изменяющие
объект на месте, должны возвращать None, давая вызывающей стороне понять,
что изменился сам объект в противовес созданию нового. Аналогичное пове-
дение демонстрирует, к примеру, функция random.shuffle, которая пере

In [ ]:
fruits = ['grape', 'raspberry', 'apple', 'banana']
print(fruits)

new_list = sorted(fruits)

print(new_list)
new_list = sorted(fruits, reverse=True)

print(new_list)

list.sort(fruits)

print(fruits)

['grape', 'raspberry', 'apple', 'banana']
['apple', 'banana', 'grape', 'raspberry']
['raspberry', 'grape', 'banana', 'apple']
['apple', 'banana', 'grape', 'raspberry']


The Key Difference
sorted() returns a new sorted list while leaving the original unchanged.
list.sort() sorts the list in-place (modifies the original list) and returns None.


When to Use Each
Feature	sorted()	list.sort()
Returns	New sorted list	None
Original list	Unchanged	Modified
Memory	Uses extra memory	More memory efficient
Use case	Keep original, need sorted copy	Don't need original anymore



In [52]:
import numpy as np

a = np.arange(12)
print(a)

type(a)

print('--'*10)

print(a.shape)
a.shape = 3, 4
print(a.shape)
print(a)
print('--'*10)
print(a[2])

print('--'*10)

print(a[:,1])
print(a[:,2])
print(a[:,3])

print('--'*10)

b = a.transpose()

print(b)

print('--'*10)

print(b[-1])
print(b[-2])
print(b[-3])

print('--'*10)

print(b / 2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
--------------------
(12,)
(3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--------------------
[ 8  9 10 11]
--------------------
[1 5 9]
[ 2  6 10]
[ 3  7 11]
--------------------
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
--------------------
[ 3  7 11]
[ 2  6 10]
[1 5 9]
--------------------
[[0.  2.  4. ]
 [0.5 2.5 4.5]
 [1.  3.  5. ]
 [1.5 3.5 5.5]]
